# Site settings
title: Hi! My name is Richard.
description: 'I am an aspiring data scientist and machine learning practitioner.'
url: 'richardcsuwandi.github.io'
baseurl: '/my-website'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Richard Cornelius Suwandi'
  email: richardcsuwandi@gmail.com
  twitter_username: richardcsuwandi
  // facebook_username: joshgerdes
  github_username: richardcsuwandi
  linkedin_username: richardcsuwandi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
