const { test, expect } = require('@playwright/test')

test('homepage collections expand without nested scrolling', async ({ page }) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  const region = page.getByRole('region', { name: 'Selected research papers' })
  const cards = region.locator('.blog-post-card-horizontal:visible')
  await expect(cards).toHaveCount(3)
  const toggle = page.getByRole('button', { name: 'Show all papers' })
  await toggle.click()
  await expect(cards).toHaveCount(await region.locator('.blog-post-card-horizontal').count())
  await expect(region).toHaveCSS('overflow-y', 'visible')
  await page.getByRole('button', { name: 'Show fewer papers' }).click()
  await expect(cards).toHaveCount(3)
  await expect(page.getByRole('button', { name: 'Show all papers' })).toBeFocused()
  const abstract = region.getByRole('button', { name: 'Abstract', exact: true }).first()
  await abstract.click()
  const panel = page.locator(`[id="${await abstract.getAttribute('aria-controls')}"]`)
  await expect(panel).toBeVisible()
  await expect(region).toHaveCSS('max-height', 'none')
  await expect(page.locator('.opensource-card:visible')).toHaveCount(6)
  await expect(page.locator('#news-list .news-card:visible')).toHaveCount(5)
})

test('expanding a collection moves keyboard focus into the revealed content', async ({ page }) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  const region = page.getByRole('region', { name: 'Selected research papers' })
  const firstNewItem = region.locator('.bibliography > li').nth(3)
  const firstControl = firstNewItem.getByRole('button', { name: 'Abstract', exact: true })
  const toggle = page.getByRole('button', { name: 'Show all papers' })
  await toggle.focus()
  await page.keyboard.press('Enter')
  await expect(firstControl).toBeFocused()
  await expect(firstControl).toBeInViewport()
  await page.keyboard.press('Tab')
  expect(await firstNewItem.evaluate(el => el.contains(document.activeElement))).toBe(true)
})
