const { test, expect } = require('@playwright/test')

test('abstract disclosure works with keyboard and rapid toggles', async ({ page }) => {
  await page.goto('/research/')
  const trigger = page.getByRole('button', { name: 'Abstract', exact: true }).first()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  const panel = page.locator(`[id="${await trigger.getAttribute('aria-controls')}"]`)
  await expect(panel).toBeHidden()
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(panel).toBeVisible()
  await page.keyboard.press('Space')
  await expect(panel).toBeHidden()
  await trigger.evaluate(el => {
    el.click()
    el.click()
    el.click()
  })
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(panel).toBeVisible()
  await expect(trigger).toBeFocused()
})

test('additional authors can be expanded and collapsed without losing focus', async ({ page }) => {
  await page.goto('/research/', { waitUntil: 'domcontentloaded' })
  const trigger = page.locator('button.more-authors-toggle').first()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  const panel = page.locator(`[id="${await trigger.getAttribute('aria-controls')}"]`)
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(panel).toBeVisible()
  await expect(trigger).toHaveText('Fewer authors')
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Space')
  await expect(panel).toBeHidden()
  await expect(trigger).toHaveText(/more authors/)
})
